site_name: 院秘档案
repo_url: https://github.com/Hzeristo/SSoCKC
repo_name: SSoCKC

extra_css:
  - stylesheets/extra.css

theme:
  logo: assets/logo1.png
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: ckc_red
      toggle:
        icon: material/weather-night
        name: 暗色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: ckc_red
      toggle:
        icon: material/weather-sunny
        name: 亮色模式
  language: zh
  features:
    - header.autohide
    - content.code.copy
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.path
  
    
  icon:
    repo: fontawesome/brands/git-alt
    
plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Hzeristo/SSoCKC

markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - attr_list
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6

nav:
  - 主页: index.md
  - 档案: 
    - archive/index.md
    - 宣传品&物料:
      - 海报: 
        - 纳新: archive/advertise/poster/纳新.md
        - 竺山论剑: archive/advertise/poster/竺山论剑.md
        - 竺林论道: archive/advertise/poster/竺林论道.md
        - 跨年夜: archive/advertise/poster/跨年夜.md
      - PPT:
        - 竺林论道: archive/advertise/ppt/竺林论道.md
        - 竺山论剑: archive/advertise/ppt/竺山论剑.md
      - 邀请函:
          - 金城/蔡建永/刘翰青/潘哲君/赵行: archive/advertise/invitation/金城-同模板.md
      - 发言稿:
        - 第9期竺林论道: archive/advertise/speech/第9期竺林论道.md
        - 第11期竺林论道: archive/advertise/speech/第11期竺林论道.md
        - 第45期竺山论剑: archive/advertise/speech/第45期竺山论剑.md
        - 第46期竺山论剑: archive/advertise/speech/第46期竺山论剑.md
      - 手卡&投屏&其他: archive/advertise/varied/soon.md
    - 新闻稿: 
      - 专业推文&院友资讯: 
        - 2023~2024专业推文: archive/article/varied/2023~2024年度专业推文.md
      - 院友专访: 
        - 金城: archive/article/visit/金城.md
      - 预热推文&总结推文:
        - 第45期竺山论剑总结推文: archive/article/activity/第45期竺山论剑总结推文.md
    - 策划案:
      - 竺山论剑:
        - 第45期竺山论剑: archive/plan/forum/第45期竺山论剑.md
        - 第46期竺山论剑: archive/plan/forum/第46期竺山论剑.md
      - 竺林论道:
        - 第9期竺林论道: archive/plan/salon/第9期竺林论道.md
        - 第10期竺林论道: archive/plan/salon/第10期竺林论道.md
        - 第11期竺林论道: archive/plan/salon/第11期竺林论道.md
      - 其他:
        - 2024跨年夜: archive/plan/varied/2024跨年夜.md
    - 手册&指南:
      - 工作手册: 
        - archive/info/manual/index.md
      - 活动指南:
        - archive/info/instructions/大型活动指南.md
    - 材料:
      - 费用&报销: 
        - archive/material/expense/expense.md
      - 设计组件:
        - archive/material/widget/index.md
  - 活动回顾: 
    - 院友专访: 
      - activity/visit/金城/金城.md
    - 竺山论剑: 
      - activity/forum/45th/第45期竺山论剑.md
    - 竺林论道: 
      - activity/salon/9th/第9期竺林论道.md
    - 其他活动:
      - activity/varied/2024y/2024跨年夜.md
  - 院友资料:
    - alumni/index.md
  - 管理: 
    - 使用指南: help.md
    - 维护须知: edit.md
    - 关于: about.md
    - 免责声明: disclaimer.html

copyright: Copyright &copy; 2024 宋瑞泽 All Rights Reserved.

