site_name: 院秘档案
repo_url: https://github.com/Hzeristo/SSoCKC
repo_name: SSoCKC

extra_css:
  - stylesheets/extra.css

theme:
  logo: assets/logo1.png
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: ckc_red
      toggle:
        icon: material/weather-night
        name: 暗色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: ckc_red
      toggle:
        icon: material/weather-sunny
        name: 亮色模式
  language: zh
  features:
    - header.autohide
    - content.code.copy
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.path
    - navigation.indexes
    
  icon:
    repo: fontawesome/brands/git-alt
    
plugins:
  - search

markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - attr_list
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - javascripts/tex-mml-chtml.js
  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - 主页: index.md
  - 档案:
    - 新闻稿: 
      - archive/article/article.md 
    - 策划案: 
      - archive/plan/plan.md
  - 关于: about.md
